# Generated by Django 5.2.6 on 2025-09-30 17:59

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='time',
        ),
        migrations.AddField(
            model_name='medication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medication',
            name='time_per_day',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AddField(
            model_name='medication',
            name='times',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='medication',
            name='dosage',
            field=models.PositiveIntegerField(help_text='Dosage in milligrams', validators=[django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='medication',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='DAILY', max_length=10),
        ),
    ]
