# Generated by Django 5.2.6 on 2025-10-01 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_remove_medication_time_medication_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='time_per_day',
            new_name='times_per_day',
        ),
    ]
