# Generated by Django 5.2.6 on 2025-10-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_pushsubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushsubscription',
            name='auth',
        ),
        migrations.RemoveField(
            model_name='pushsubscription',
            name='p256dh',
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='keys',
            field=models.JSONField(default=dict),
        ),
    ]
