# Generated by Django 5.2.6 on 2025-10-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0005_remove_pushsubscription_auth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushsubscription',
            name='keys',
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='auth',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='p256dh',
            field=models.TextField(blank=True, default=''),
        ),
    ]
