# Generated by Django 5.2.6 on 2025-10-03 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0006_remove_pushsubscription_keys_pushsubscription_auth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushsubscription',
            name='auth',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='p256dh',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date', models.DateField()),
                ('sent_time', models.CharField(max_length=5)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.medication')),
            ],
            options={
                'unique_together': {('medication', 'sent_date', 'sent_time')},
            },
        ),
    ]
