# Generated by Django 5.2.6 on 2025-10-04 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_doselog'),
        ('medicines', '0007_alter_pushsubscription_auth_and_more'),
    ]

    operations = [
    ]
