# Generated by Django 5.2.6 on 2025-10-05 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0008_merge_20251004_0955'),
        ('medicines', '0009_alter_doselog_options_googlecredentials'),
    ]

    operations = [
    ]
