# Generated by Django 5.2.6 on 2025-10-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0010_merge_20251005_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='google_event_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='googlecredentials',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlecredentials',
            name='scopes',
            field=models.TextField(default='https://www.googleapis.com/auth/calendar.events'),
        ),
    ]
